### ISSUE TITLE
[Q] Does it uses reflection?

### ISSUE THREAD

**Issue by rostopira** [mylisabox/remote_ui#1]
I'm using [obfuscation](https://flutter.dev/docs/deployment/obfuscate).
As per docs:

> Code that relies on matching specific class, function, or library names will fail.

So, does this package works with obfuscation enabled?

Thanks in advance.

**Comment by jaumard** [comment]
That's a good question!!! I think the only matching is done on the json representation, so that will not be impacted by the obfuscation. It will need some tests to be sure but I'll say that it will work even with obfuscation.

**Comment by rostopira** [comment]
Thanks for response. I'm gonna test it out myself and report the results =)

**Comment by jaumard** [comment]
I've check quickly the code I'm pretty confident it should work :) but if not let me know and I'll check where it doesn't.

**Comment by jaumard** [comment]
And to answer the question on the title no it doesn't use reflection at all, it use json tree representation only and then map it to the flutter widget equivalent
