### ISSUE TITLE
help in factory

### ISSUE THREAD

**Issue by kamil-bit** [mylisabox/remote_ui#4]
could you write me what i should do in this task ?

Add the factory to the RemoteManagerWidget:

RemoteManagerWidget(
    parsers: [RemoteIpCameraFactory()],
    child: RemoteWidget(...)
)

and could you write what os is supported in pub dev ?

**Comment by jaumard** [comment]
It's pure dart so all OS are supported :) 

Just the IP camera doesn't work on the web for now... there is an issue with Dart itself. 

I don't really understand your question, can you explain what's your problem? Did you take a look at the example ? Might help you better understand how to use it

**Comment by kamil-bit** [comment]
Ok i know. i had to add manually this line import 'package:remote_ui/remote_ui.dart';
when i click Alt+Enter for RemoteManagerWidget i couldn't .  Now everything works

**Comment by kamil-bit** [comment]
everything works
